[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "onemod"
version = "0.1.0"
description = "A pipeline package for estimating scalar quantity by leveraging covariates and correlations across multiple dimensions."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "IHME Math Sciences", email = "ihme.math.sciences@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "jobmon_installer_ihme",
    "fire",
    "loguru",
    "modrover @ git+https://github.com/ihmeuw-msca/modrover.git@v0.1.3",
    "regmodsm @ git+https://github.com/ihmeuw-msca/regmodsm.git@v0.1.1",
    "pandas < 2.0",
    "pyarrow",
    "pydantic",
    "scipy",
    "regmod == 0.1.1",
    "weighted-average == 1.1.1",
]

[project.optional-dependencies]
test = ["pytest"]
docs = ["sphinx", "sphinx-autodoc-typehints", "furo"]

[project.urls]
github = "https://github.com/ihmeuw-msca/OneMod"