# Default resources
tool_resources:
  slurm:
    queue: all.q
    cores: 1
    memory: 30G
    runtime: 1h
    project: proj_mscm

# Optional task-specific resources
task_template_resources:
  rover_covsel_modeling_template:
    slurm:
      memory: 10G
      runtime: 10m
  spxmod_modeling_template:
    slurm:
      memory: 10G
      runtime: 20m
  weave_modeling_template:
    slurm:
      memory: 10G
      runtime: 10m
  ensemble_modeling_template:
    slurm:
      memory: 10G
      runtime: 10m
