# OneMod settings
input_path: /path/to/input/data.parquet
ids: [age_group_id, location_id, sex_id, year_id]
age_group_id: [8, 9, 10]
location_id: [13, 14]
sex_id: [1, 2]
year_id: [1980, 1981, 1982]
obs: obs_rate
pred: pred_rate
holdouts: [holdout1, holdout2, holdout3]
test: test
mtype: binomial
max_attempts: 1

rover_covsel:
  groupby: [age_group_id, sex_id]
  rover:
    cov_fixed: [intercept]
    cov_exploring: [cov1, cov2, cov3]
    weights: population
  rover_fit:
    strategies: [forward]
    top_pct_score: 1.0
    top_pct_learner: 0.5

# Regmod smooth settings
regmod_smooth:
  model:
    var_groups:
      # Intercept relisted multiple times,
      # Could compress, list different dimensions/priors as sub keys
      - col: "intercept"
      - col: "intercept"
        dim: "super_region_id"
        gprior: [0, 0.35]
    weights: population
    coef_bounds:
      LDI_pc: [-inf, 0]
      education_yrs_pc: [-inf, 0]
    dims:
      - name: "age_mid"
        type: "numerical"
      - name: "super_region_id"
        type: "categorical"
  regmod_fit:
    options:
      verbose: false
      m_scale: 0.1

# WeAve settings
weave:
  max_attempts: 1
  models:
    model1:
      max_batch: 5000
      groupby: [sex_id, super_region_id]
      dimensions:
        age:
          name: age_group_id
          coordinates: age_mid
          kernel: exponential
          radius: [0.75, 1, 1.25]
        year:
          name: year_id
          kernel: tricubic
          exponent: [0.5, 1, 1.5]
        location:
          name: location_id
          coordinates: [super_region_id, region_id, location_id]
          kernel: depth
          radius: [0.7, 0.8, 0.9]
    model2:
      groupby: [age_group_id, sex_id]
      dimensions:
        year:
          name: year_id
          kernel: tricubic
          exponent: [0.5, 1, 1.5]
        location:
          name: location_id
          kernel: identity
          distance: dictionary
          distance_dict: [/path/to/distance_dict1.parquet, /path/to/distance_dict2.parquet]

# Ensemble settings
ensemble:
  max_attempts: 1
  groupby: [sex_id, super_region_id]
  metric: rmse
  score: neg_exp
  top_pct_score: 1
  top_pct_model: 1
