name: build-to-pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_to_pages:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install .[docs] --upgrade pip
      - name: Generate API docs & Build sphinx documentation
        run: |
          git fetch --tags
          git checkout publish-docs
          git pull
	  cd docs
          echo "Calling build.py"
          python build.py
          echo "Done Calling build.py"
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs-out/pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
